Agent:
  PR_url: https://api.github.com/repos/Opentrons/opentrons/pulls/14488
  api_key: sk-wvvB8thiOVcpwJw1i4OI4FqFSItWyC5IePz3hAgrOJ0Jh1MY
  diff_url: https://api.github.com/repos/Opentrons/opentrons/pulls/14488/files
  llm_model: gpt-4o
  llm_url: https://api.chatanywhere.tech/v1/chat/completions
  output_dir: ./result/tot_test/opentrons/prompt_v1
  output_file_name: ''
CKG:
  graph_pkl_dir: ./CKG/opentrons_graph.pkl
  project_dir: /home/veteran/projects/multiAgent/TestPlanAgent/test_projects/opentrons
Judge:
  pull_number: '14488'
  tmp_dir: ./result/tot_test/opentrons/tmp/
