Agent:
  PR_url: https://api.github.com/repos/Opentrons/opentrons/pulls/16571
  api_key: sk-6072ffbc181542f2862a1fd04d8291c0
  diff_url: https://api.github.com/repos/Opentrons/opentrons/pulls/16571/files
  llm_model: qwen2.5-coder-32b-instruct
  llm_url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  output_dir: ./result/tot_test/opentrons/prompt_v1
  output_file_name: gpt-4o_20250315_121546.txt
CKG:
  graph_pkl_dir: ./CKG/opentrons_graph.pkl
  project_dir: /home/veteran/projects/multiAgent/TestPlanAgent/test_projects/opentrons
Judge:
  tmp_dir: ./result/tot_test/opentrons/tmp/
